### ISSUE TITLE
Throwing exceptions

### ISSUE THREAD

**Issue by Curadise** [syedhussim/php-sapb1-v2#2]
I have been playing with the new v2 library, so far so good
But it does not seem to catch any errors. Only with a failed login, the script throws an exception
All other SAP errors (e.g. Item is inactive), do not throw any errors

Since it was in the v1 version, is this by design? 
If yes, what is the main reason you choose for this approach?

Kind regards, Maurice

**Comment by syedhussim** [comment]
Hi Maurice, yes this is by design. In version 1, the code checked for a specific response codes (200,201 and 204 for the create method) and threw an exception if the response codes were anything else.  The issue there was that, during the initial stage of writing the library, I didn't know that other response codes could be returned. (I though the SL only returned 200 on success).  This meant that over a period of time, I had to modify the code. 

In v2, I return a http response that includes the http code and body, this allows the implementer of the library to handle the error by looking at the http response code. 

Also in v1, you could provide a boolean value to return the http response. In this case, the exceptions will not get thrown. This was a hack job added some time later.

To avoid hacking the library for v2 in the future, I though it would be best to return the http response and let the developer handle the response in the way they want. 

Hope this helps.

**Comment by Curadise** [comment]
Ah yes, that clears things up. Thanks!
